name: event-360-consumer-business-metric-alert-monitor
version: v1alpha
type: monitor
monitor:
  schedule: '0 0 31 * *'
  type: equation_monitor
  equation:
    leftExpression:
      queryCoefficient: 1
      queryConstant: 0
      query:
        type: lens
        lens:
          dataOsInstance:
            name: exec-360-flash
            workspace: public
            sslmode: 'disable'
        ql: 
          SELECT 
            MEASURE(event-360_consumer.total_event-360) as total_event-360
            FROM
              event-360_consumer
            LIMIT 
              10
            OFFSET 
              0
        comparisonColumn: {
            name: total_event-360, # The column that you consider as the comparision column, the value of this columns will be matched against the value of the right hand expression.
            dataType: int64 # The data type
        }
    rightExpression:
      queryCoefficient: 0
      queryConstant: 1000
      query:
    operator: greater_than_equals
  incident:
    type: business-metric
    name: event-360_consumer_metric
    category: equation
    severity: info
