name: consumer-quality-checks-failed-monitor
version: v1alpha
type: monitor
tags:
  - dataos:type:resource
  - dataos:layer:user
description: Alerts! Recent consumer-aligned quality check for event-360 has resulted in a failure due to ambiguities found in the data. It appears there are inconsistencies or inaccuracies that require your immediate attention.
layer: user
monitor:
  schedule: '*/30 * * * *'
  type: equation_monitor
  equation:
    leftExpression:
      queryCoefficient: 1
      queryConstant: 0
      query:
        type: trino 
        cluster: system
        ql: 
          WITH cte AS (
            SELECT 
              CASE
                WHEN check_outcome = 'fail' THEN 0
                ELSE NULL
              END AS result,
              timestamp
            FROM
              icebase.sys01.soda_quality_checks
            WHERE
              collection = 'event-360_consumer'
              AND dataset = 'event-360_enriched'
              AND from_iso8601_timestamp(timestamp) >= (CURRENT_TIMESTAMP - INTERVAL '30' MINUTE)
          )
            SELECT 
            DISTINCT result
          FROM
            cte
          WHERE
            result IS NOT NULL
  
    rightExpression:
      queryCoefficient: 1
      queryConstant: 0
    operator: equals
  incident:
    name: consumer-soda-check-fail
    severity: high
    incident_type: consumer-soda-quality
