name: consumer-workflow-failed-monitor
version: v1alpha
type: monitor
tags:
  - dataos:type:resource
  - consumer-workflow-failed-monitor
description: Attention! The consumer-aligned workflow for event-360 has experienced a failure. Please be rest assured, we are currently investigating the cause of the failure. Your patience is appreciated as we work to resolve this issue. Please refer to the logs for additional information.
layer: user
monitor:
  schedule: '*/1 * * * *'
  type: report_monitor
  report:
    source:
      dataOsInstance:
        path: /collated/api/v1/reports/resources/runtime?id=workflow:v1:%25:public
    conditions:
      - valueComparison:
          observationType: workflow-runs
          valueJqFilter: '.value[] | {completed: .completed, phase: .phase} | select (.completed | fromdateiso8601 > (now-600)) | .phase'
          operator: equals
          value: failed
  incident:
    name: consumer-workflowfailed
    severity: high
    incident_type: consumer-workflowruntimefailure
