name: clickstream-bundle
version: v1beta
type: bundle
tags:
  - Tier.Gold
description: The purpose of the bundle is to deploy the resources of the clickstream Data Product, making it available for consumption in clickstream.
layer: "user"
bundle:
  resources:
    - id: clickstream-pipeline
      file: clickstream/clickstream/deploy/pipeline.yaml
      workspace: public
